### ISSUE TITLE
ICU for Unicode handling?

### ISSUE THREAD

**Issue by shermp** [NiLuJe/FBInk#10]
Hi @NiLuJe 

I'm mulling the idea of adding basic freetype2 support, and was having a look at the FBInk codebase to see if I could figure out how to add support, and I've noticed your rant on Kobo's broken libc with regard to unicode support.

I notice that the Kobo firmware appears to include the ICU library (libicu*.so, vers. 4.6). Have you looked into using this library for dealing with strings in FBInk?

The API documentation for ICU 4.6.1 is [here](http://icu-project.org/apiref/icu4c461/)

**Comment by NiLuJe** [comment]
I ended up skirting the issue with libu8, and, provided no-one tries to feed hopelessly broken encoding, that does the job just fine without having to massively rework how strings are handled ;).

(ICU is a very very large hammer to take care of the Unicode issue, and the fact that wchar_t is just hopelessly broken on Kobo probably doesn't help. Plus, the fact that some of our target devices either don't ship it, or ship wildly different versions is another thing against it, because bundling it is not an option: besides the fact that it's C++, and takes forever to build, libicudata is over 25MB in ICU 60.2 ;)).

**Comment by NiLuJe** [comment]
That's essentially what I ended up going with ;).

I think I may have read that very same article, (if it mentioned doing sanitization/conversions at I/O boundaries, that's the one). But with the hobbled libc, I can't really do the sanitization/conversion bit, since anything multibyte/widechar is basically borked ;).
So I'm just skipping that, and hoping really hard no-one will feed us KOI8-R or something xD.

**Comment by shermp** [comment]
It probably was the same article :p

I've been looking into this area a bit lately, because I'm trying to see if I can add differential support to my VHD library, and filepath strings there are encoded as UTF16BE.

Incidentally, do you know of any good cross platform C file path library?

**Comment by NiLuJe** [comment]
Not really, the only thing that comes to mind is C++ (namely, boost) :/.

**Comment by NiLuJe** [comment]
And I really don't want to say glib on the C side of things, because glib's weird, and I'm not even sure it'd do what you need ;).

**Comment by shermp** [comment]
Thanks for the suggestions. I didn't see anything that really struck me as being suitable for my requirements (simple though they may be; path joining and normalization).

**Comment by shermp** [comment]
I had another look at that STB link, and noticed I had missed the `stb.h` file the first time around.

Oh my... that looks just about perfect :)
