### ISSUE TITLE
K4: not working

### ISSUE THREAD

**Issue by yparitcher** [NiLuJe/FBInk#19]
every time i try to use FBInk (no matter what options) i get an error
```
[FBInk] MXCFB_SEND_UPDATE: Invalid argument
[FBInk] update_region={top=0, left=0, width=600, height=800}
[FBInk] Failed to refresh the screen!
```

thanks
if you need more info just let me know

**Comment by NiLuJe** [comment]
Is this with a self-built binary, or one of my releases?

I'll double-check on my end, but I vaguely recall having made sure I didn't break this when I consolidated Kindle support...

**Comment by NiLuJe** [comment]
Yep, no issue on my end.

How did you build it, what does the full output look like, and which exact Kindle model is that?

Because it's obviously not detecting a K4, which probably means you're running a Kobo/Cervantes build on Kindle, or there's something wonky with the K4 detection, which is strange, since there are very very few K4 variants, so, it's hard to mess up ;).

**Comment by NiLuJe** [comment]
... And yet, mess it up, I did ;p.

It's a Black K4, right?

**Comment by yparitcher** [comment]
both with the release bundled with the usbnetwork and font hack, and with the latest release 1.7.0 from the forum, this is a black K4 (2012) serial 9023

**Comment by yparitcher** [comment]
thanks, it confused me at the begining why my hacks did not respond when i installed them this time around untill i figured out they worked but just were not printing :)

**Comment by NiLuJe** [comment]
Yeah, that was indeed a very stupid oversight, my bad ;).

This binary should work
[fbink-hash19.tar.gz](https://github.com/NiLuJe/FBInk/files/2507308/fbink-hash19.tar.gz) :).

**Comment by yparitcher** [comment]
it is working now

**Comment by NiLuJe** [comment]
Thanks!

Keep it around, because it may be some time until the next round of snapshots update ;).
