### ISSUE TITLE
Can't build with `make LINUX=true` - undefined reference to get_hwd_mode()

### ISSUE THREAD

**Issue by llandsmeer** [NiLuJe/FBInk#42]
Hi, I just came across FBInk, which looks exactly like what I'm searching for!

However, while trying to build a linux build, I got a lot of `undefined reference to get_hwd_mode` messages. Moving `get_hwd_mode` and `hwd_to_string` outside the `#ifndef FBINK_FOR_LINUX`
got everything working again and I can write to the framebuffer now. I suppose it's not a good fix (those ifdefs must be there for a reason), but maybe this helps in some way :)

Commit: 747530d29a87c01917780dd962f5e0752559fdc4

Diff (just 2 lines moved):

```diff
diff --git a/fbink.c b/fbink.c
index 3f99c50..bb779b8 100644
--- a/fbink.c
+++ b/fbink.c
@@ -5448,6 +5448,7 @@ static const char*
        }
 }
 #      endif    // FBINK_FOR_KINDLE
+#endif    // !FBINK_FOR_LINUX

 // Convert our public HW_DITHER_INDEX_T values to an appropriate mxcfb dithering mode constant
 static int
@@ -5511,7 +5512,6 @@ static const char*
                        return "Unknown";
        }
 }
-#endif    // !FBINK_FOR_LINUX

 // Small public wrapper around refresh(), without the caller having to depend on mxcfb headers
 int
diff --git a/fbink_internal.h b/fbink_internal.h
index dea4cd1..87a9f69 100644
--- a/fbink_internal.h
+++ b/fbink_internal.h
@@ -593,9 +593,9 @@ static const char* wfm_to_string(uint8_t);
 static const char* kindle_wfm_to_string(uint32_t);
 static const char* kindle_zelda_wfm_to_string(uint32_t);
 #      endif
+#endif
 static int         get_hwd_mode(uint8_t);
 static const char* hwd_to_string(uint8_t);
-#endif

 // For identify_device, which we need outside of fbink_device_id.c ;)
 #ifndef FBINK_FOR_LINUX
```

Kind regards,
Lennart

**Comment by NiLuJe** [comment]
Whoops, that's quite possibly the only target I failed to check, thanks ;).

**Comment by NiLuJe** [comment]
Thanks, fixed via fe024f2a4641c78137c247dd5c27f235706ba175.

As a sidenote, as you may have surmised by now, we're mainly concerned with eInk framebuffers, so the "plain" Linux fb behavior isn't very well tested (I basically check from time to time that it doesn't do anything obviously stupid on my own desktop's EFI fb).

Of particular note, I don't have access to anything with a 24bpp fb (and switchign an eInk device to that mode yielded... strange results ^^), so that codepath is a big question mark.

The closest I've got is my desktop's amdgpudrmfb, which is 24bpp packed in RGB32, which will happily go through the 32bpp codepath ;).

**Comment by llandsmeer** [comment]
That's quick, can confirm it works! I intend to develop some apps for my new Libra H2O, so those shouldn't be a problem. The linux build option just shortens the iteration time. Thanks a lot for creating and maintaining this project!

**Comment by NiLuJe** [comment]
Cool, thanks for the feedback, and don't hesitate to ping me if you have any question ;).
